about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("posts/", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group"),
    path("new", views.new_post, name="new_post"),
    path("", views.index, name="index"),
    path("follow/", views.follow_index, name="follow_index"),
    path("<str:username>/follow/", views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow, name="profile_unfollow"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path("<username>/<int:post_id>/comment", views.add_comment, name="add_comment"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
        help_text='Заголовок'
    )
    slug = models.SlugField(
        max_length=75,
        unique=True,
        verbose_name='Группа',
        help_text='Название группы'
    )
    description = models.TextField(
        blank=True,
        verbose_name='Описание',
        help_text='Описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        blank=True,
        null=True,
        verbose_name='Текст',
        help_text='Введите текст вашего поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        help_text='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберете группу'
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name='Изображение',
        help_text='Загрузите изображение'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        # str_return = (
        #    str(self.author) + ' / ' +
        #    str(self.pub_date.strftime('%d.%m.%Y')) + ' / ' +
        #    str(self.group) + ' / ' +
        #    str(self.text)[0:50] + '...'
        # )
        # Для тестов возврат 15ти символов текста
        str_return = str(self.text)[:15]
        return str_return


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='comments',
        verbose_name='Запись',
        help_text='Запись'
    )

    text = models.TextField(
        blank=True,
        null=True,
        verbose_name='Комментарий',
        help_text='Введите текст вашего комментария'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Автор'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        help_text='Дата публикации комментария'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.text)[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
        help_text='Подписчик'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Автор'
    )

posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    text = forms.CharField(
        label='Текст',
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        required=True,
        help_text='Введите текст вашего поста'
    )

    class Meta:
        model = Post
        fields = [
            'group',
            'text',
            'image',
        ]
        labels = {
            'group': 'Группы',
        }
        attrs = {
            'group': 'form-control',
        }


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        label='Комментарий',
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        required=True,
        help_text='Введите вашего комментария'
    )

    class Meta:
        model = Comment
        fields = [
            'text',
        ]

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def index(request):
    post_list = Post.objects.select_related('group').order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'group': group,
        'posts': posts,
        'paginator': paginator,
    }
    return render(request, 'group.html', context)


@login_required
def new_post(request):
    if request.method != 'POST':
        form = PostForm()
        return render(request, 'new.html', {'form': form})
    form = PostForm(request.POST)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('index')
    form = PostForm()
    return render(request, 'new.html', {'form': form})


def profile(request, username):
    user_id = get_object_or_404(User, username=username)
    post_list = Post.objects.select_related('author').filter(
        author=user_id).order_by('-pub_date')
    count = Post.objects.select_related(
        'author').filter(author=user_id).count()
    countfollowing = Follow.objects.filter(
        user=user_id).count()
    countfollower = Follow.objects.filter(
        author=user_id).count()
    if request.user.is_authenticated:
        following = False
        if Follow.objects.filter(author=user_id, user=request.user).exists():
            following = True
    else:
        following = False
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'author': user_id,
        'count': count,
        'paginator': paginator,
        'profile': user_id,
        'countfollower': countfollower,
        'countfollowing': countfollowing,
        'following': following,
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    username = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author=username)
    countfollowing = Follow.objects.filter(
        user=username).count()
    countfollower = Follow.objects.filter(
        author=username).count()
    count = Post.objects.select_related(
        'author').filter(author=username).count()
    all_comments = Comment.objects.filter(post_id=post_id)
    if request.method != 'POST':
        form = CommentForm()
        context = {
            'post': post,
            'author': username,
            'count': count,
            'username': username,
            'post_id': post_id,
            'comments': all_comments,
            'form': form,
            'countfollower': countfollower,
            'countfollowing': countfollowing,
        }
        return render(request, 'post.html', context)
    form = CommentForm(request.POST)
    if form.is_valid():
        comments = form.save(commit=False)
        comments.author = request.user
        comments.post_id = post_id
        form.save()
        return redirect('post', username=username, post_id=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'author': username,
        'count': count,
        'username': username,
        'post_id': post_id,
        'comments': all_comments,
        'form': form,
    }
    return render(request, 'post.html', context)


@login_required
def add_comment(request, username, post_id):
    username = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author=username)
    countfollowing = Follow.objects.filter(
        user=username).count()
    countfollower = Follow.objects.filter(
        author=username).count()
    count = Post.objects.select_related(
        'author').filter(author=username).count()
    all_comments = Comment.objects.filter(post_id=post_id)
    if request.method != 'POST':
        form = CommentForm()
        context = {
            'post': post,
            'author': username,
            'count': count,
            'username': username,
            'post_id': post_id,
            'comments': all_comments,
            'form': form,
            'countfollower': countfollower,
            'countfollowing': countfollowing,
        }
        return render(request, 'post.html', context)
    form = CommentForm(request.POST)
    if form.is_valid():
        comments = form.save(commit=False)
        comments.author = request.user
        comments.post_id = post_id
        form.save()
        return redirect('post', username=username, post_id=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'author': username,
        'count': count,
        'username': username,
        'post_id': post_id,
        'comments': all_comments,
        'form': form,
    }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    username = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author=username)
    if request.user != post.author:
        return redirect('post', username=username, post_id=post_id)
    if request.method != 'POST':
        form = PostForm(instance=post)
        return render(request,
                      'post_new.html',
                      {
                          'form': form,
                          'post': post,
                      }
                      )
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        form.save()
        return redirect('post', username=username, post_id=post_id)
    form = PostForm()
    context = {
        'form': form,
        'post': post,
    }
    return render(request, 'post_new.html', context)


@login_required
def follow_index(request):
    follow_list = []
    follow_list_id = Follow.objects.filter(user=request.user).in_bulk()
    for i in follow_list_id:
        follow_list.append(follow_list_id[i].author)
    post_list = Post.objects.filter(author__in=follow_list)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'page': page,
        'paginator': paginator,
    }
    return render(request, "follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return follow_index(request)
    Follow.objects.get_or_create(user=request.user, author=author)
    return profile(request, username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return profile(request, username)
    Follow.objects.filter(author=author, user=request.user).delete()
    return profile(request, username)


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)

templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    {% load static %}      
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    {% include 'nav.html' %}
    <main>
      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
    {% include 'footer.html' %}
  </body>
</html>

templates/comments.html
{% load user_filters %} {% if user.is_authenticated %}
<div class="card my-4">
  <form method="post">
    {% csrf_token %}
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <div class="form-group">{{ form.text|addclass:"form-control" }}</div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
  </form>
</div>
{% endif %} {% for item in comments %}
<div class="media card mb-4">
  <div class="media-body card-body">
    <h5 class="mt-0">
      <a
        href="{% url 'profile' item.author.username %}"
        name="comment_{{ item.id }}">
        {{ item.author.username }}
      </a>
    </h5>
    <p>{{ item.text | linebreaksbr }}</p>
  </div>
</div>
{% endfor %}

templates/follow.html
{% extends "base.html" %} 
{% block title %} Последние обновления ваших избранных авторов {% endblock %}
{% block content %}
  {% load cache %}
    {% cache 20 index_page %}
      <div class="container">
        {% include "menu.html" with index=True %}
        <h1>Последние обновления ваших избранных авторов на сайте</h1>
          {% for post in page %}
            {% include "post_item.html" with post=post %}
          {% endfor %}
      </div>
      {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
      {% endif %}
  {% endcache %}
{% endblock %}

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
  </p>
  <p class="m-0 text-dark text-center">
    Социальная сеть <span style="color: red">Ya</span>tube © {% now "Y" %}, все
    права защищены.
  </p>
</footer>

templates/group.html
{% extends "base.html" %} 
{% block title %}Записи сообщества {{ group }}{% endblock %} 
{% block content %}
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in posts %}
      <h3 class="h3">
        Автор: <a class="p-2 text-dark" href="{% url 'profile' post.author.username %}">{{ post.author.get_full_name }}</a>, 
        группа: <a class="card-link muted" href="{% url 'group' post.group.slug %}">#{{ post.group.title }}</a>        
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </h3>
      {% include "post_item.html" with post=post %} 
    {% endfor %}
    <hr />
    </div>
    {% if page.has_other_pages %} 
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %} 
{% endblock %}

templates/index.html
{% extends "base.html" %} 
{% block title %} Последние обновления {% endblock %}
{% block content %}
  {% load cache %}
  {% cache 20 index_page %}
    <div class="container">
      {% include "menu.html" with index=True %}
      <h1>Последние обновления на сайте</h1>
        {% for post in page %}
          {% include "post_item.html" with post=post %}
        {% endfor %}
    </div>
    {% if page.has_other_pages %}
      {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
  {% endcache %}
{% endblock %} 

templates/menu.html
{% if user.is_authenticated %}
<div class="row">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
        Все авторы
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
        Избранные авторы
      </a>
    </li>
  </ul>
</div>
{% endif %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
    {% if user.is_authenticated %}
      <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
      Пользователь: {{ user.username }}.
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

templates/new.html
{% extends "base.html" %}
{% block title %}Добавить новую запись{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-10 p-5">
        <div class="card">
            <div class="card-header">Новая запись</div>
            <div class="card-body">
                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error|escape }}
                </div>
                {% endfor %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% autoescape on %}
                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-2 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-8">
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                            </div>
                        {% endfor %}
                    {% endautoescape %}
                    <div class="col-md-8 offset-md-5">              
                        <button type="submit" class="btn btn-primary">
                            Создать запись
                        </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
      </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %} 
      {% for i in page.paginator.page_range %} 
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %} 
      {% endfor %} 
      {% if page.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/post.html
{% extends "base.html" %} 
{% block title %}Записи {{ author.get_full_name }} {% endblock %} 
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">{{ author.get_full_name }}</div>
          <div class="h3 text-muted">{{ author }}</div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ countfollower }} <br />
              Подписан: {{ countfollowing }}
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">Записей: {{ count }}</div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-md-9">
      {% include "post_item.html" with post=post %} 
      {% include "comments.html" %} 
      {% include "paginator.html" %}
    </div>
  </div>
</main>
{% endblock %}

templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <div class="card-body">
    <p class="card-text">
      <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>
    {% if post.group %}
      <a class="card-link muted" href="{% url 'group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
    {% endif %}
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>          
        {% endif %}
      </div>
      <div class="btn-group">
          <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>  
          {% if user == post.author %}
            <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
              Редактировать
            </a>
          {% endif %}        
      </div>
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div> 

templates/post_new.html
{% extends "base.html" %}
{% block title %}Редактировать запись{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-10 p-5">
        <div class="card">
            <div class="card-header">Редактировать запись</div>
            <div class="card-body">
                {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error|escape }}
                </div>
                {% endfor %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% autoescape on %}
                        {% for field in form %}
                            <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-2 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-8">
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                            </div>
                        {% endfor %}
                    {% endautoescape %}
                    <div class="col-md-8 offset-md-5">              
                        <button type="submit" class="btn btn-primary">
                            Отредактировать запись
                        </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/profile.html
{% extends "base.html" %} 
{% block title %}Записи {{ author.get_full_name }} 
{% endblock %} 
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
            <a class="p-2 text-dark" href="{% url 'profile' author.username %}">@{{ author }}</a>
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ countfollower }} <br />
              Подписан: {{ countfollowing }}
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <!-- Количество записей -->
              Записей: {{ count }}
            </div>
          </li>
        </ul>
        <li class="list-group-item">
          {% if following %}
          <a class="btn btn-lg btn-light" href="{% url 'profile_unfollow' profile.username %}" role="button">
            Отписаться
          </a>
          {% else %}
          <a class="btn btn-lg btn-primary" href="{% url 'profile_follow' profile.username %}" role="button">
            Подписаться
          </a>
          {% endif %}
        </li>
      </div>
    </div>
    <div class="col-md-9">
      {% for post in page %} 
        {% include "post_item.html" with post=post %} 
      {% endfor %} 
      {% include "paginator.html" %}
    </div>
  </div>
</main>
{% endblock %}